# Generated by Django 5.1.15 on 2026-05-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='speakerapplication',
            name='unique_speaker_application_email',
        ),
        migrations.AddField(
            model_name='speakerapplication',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsorinquiry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='speakerapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('email',), name='unique_speaker_application_email'),
        ),
    ]
