# Generated by Django 5.1.15 on 2026-05-31 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_featuredspeaker_speaker_application'),
        ('outreach', '0004_speaker_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerapplication',
            name='cv_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_cvs', to='cms.mediaasset'),
        ),
        migrations.AddField(
            model_name='speakerapplication',
            name='occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='speakerapplication',
            name='role',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
