# Generated by Django 5.1.15 on 2026-05-23 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('flow', models.CharField(choices=[('open', 'Open registration'), ('approval', 'Approval required')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_open_for_registration', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pass_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PassRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=32)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('organization_website', models.URLField(blank=True)),
                ('contribution_statement', models.TextField(blank=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='pass_registrations', to=settings.AUTH_USER_MODEL)),
                ('pass_type', models.ForeignKey(db_column='pass_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='registrations.passtype')),
            ],
            options={
                'db_table': 'pass_registrations',
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_pass_registration_per_user')],
            },
        ),
    ]
