# Generated by Django 5.1.15 on 2026-05-23 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='passregistration',
            name='unique_pass_registration_per_user',
        ),
        migrations.AddField(
            model_name='passregistration',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='passtype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='passtype',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name='passregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user',), name='unique_pass_registration_per_user'),
        ),
        migrations.AddConstraint(
            model_name='passtype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_pass_type_slug_alive'),
        ),
    ]
