# Generated by Django 5.1.15 on 2026-05-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sitesection',
            new_name='cms_site_se_page_3878aa_idx',
            old_name='cms_site_se_page_8a1f2c_idx',
        ),
    ]
