# Generated by Django 5.1.15 on 2026-05-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_rename_cms_site_se_page_8a1f2c_idx_cms_site_se_page_3878aa_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesection',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='sitesection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_cms_site_section_slug_alive'),
        ),
    ]
