# Generated by Django 5.1.15 on 2026-05-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_featuredspeaker_featuredsponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredspeaker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='featuredsponsor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
