# Generated by Django 5.1.15 on 2026-06-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_attendeevoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='is_private',
            field=models.BooleanField(default=False, help_text='When true, the file is only accessible via the secure proxy view.'),
        ),
    ]
