# Generated by Django 5.1.15 on 2026-05-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverification'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_user_email_alive',
        ),
        migrations.RenameIndex(
            model_name='emailverification',
            new_name='email_verif_email_5c072e_idx',
            old_name='email_verif_email_purpose_idx',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
