# Generated by Django 5.1.15 on 2026-05-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_admin_role_and_staff_invite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordreset',
            new_name='password_re_user_id_fe9ce8_idx',
            old_name='password_re_user_id_6a8f2a_idx',
        ),
    ]
