# Generated by Django 5.1.15 on 2026-06-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_participant_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinvite',
            name='admin_role',
            field=models.CharField(choices=[('content_manager', 'Content manager'), ('submissions_reviewer', 'Submissions reviewer'), ('user_manager', 'User manager'), ('operations', 'Operations (content + submissions)'), ('finance', 'Finance')], max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('content_manager', 'Content manager'), ('submissions_reviewer', 'Submissions reviewer'), ('user_manager', 'User manager'), ('operations', 'Operations (content + submissions)'), ('finance', 'Finance')], db_index=True, max_length=32, null=True),
        ),
    ]
