# Generated by Django 5.1.15 on 2026-06-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_referen_2b1f06_idx',
            old_name='payments_referen_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_status_c7b1f9_idx',
            old_name='payments_status_idx',
        ),
    ]
