# Generated by Django 5.1.15 on 2026-06-12 18:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_payments_referen_idx_payments_referen_2b1f06_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('momo', 'Mobile Money'), ('bank', 'Bank Transfer')], max_length=32)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=100)),
                ('bank_or_network', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('proof_notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(db_column='requested_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'withdrawal_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
