# Generated by Django 5.1.15 on 2026-05-22 17:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('event_support', 'Event & Community Support'), ('creative_media', 'Creative & Multimedia')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'volunteer_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=32)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('skills_summary', models.TextField()),
                ('motivation', models.TextField()),
                ('availability', models.JSONField(default=dict)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('portfolio_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('code_of_conduct_accepted', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_applications', to=settings.AUTH_USER_MODEL)),
                ('assigned_role', models.ForeignKey(blank=True, db_column='assigned_role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to='volunteers.volunteerrole')),
            ],
            options={
                'db_table': 'volunteer_applications',
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplicationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='volunteers.volunteerapplication')),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'volunteer_application_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplicationPreferredRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteerapplication')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteerrole')),
            ],
            options={
                'db_table': 'volunteer_application_preferred_roles',
            },
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='preferred_roles',
            field=models.ManyToManyField(blank=True, related_name='applications', through='volunteers.VolunteerApplicationPreferredRole', to='volunteers.volunteerrole'),
        ),
        migrations.AddConstraint(
            model_name='volunteerapplicationpreferredrole',
            constraint=models.UniqueConstraint(fields=('application', 'role'), name='unique_application_role'),
        ),
        migrations.AddConstraint(
            model_name='volunteerapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['submitted', 'under_review', 'interview', 'accepted'])), fields=('user',), name='unique_active_volunteer_application_per_user'),
        ),
    ]
