# Generated by Django 5.1.15 on 2026-05-31 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_featuredspeaker_speaker_application'),
        ('volunteers', '0003_remove_volunteerapplication_unique_volunteer_application_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='cv_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_cvs', to='cms.mediaasset'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='profile_image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_photos', to='cms.mediaasset'),
        ),
        migrations.AlterField(
            model_name='volunteerrole',
            name='category',
            field=models.CharField(choices=[('event_support', 'Event & Community Support'), ('creative_media', 'Creative & Multimedia'), ('tech_training', 'Technical & Training')], max_length=32),
        ),
    ]
