# Generated by Django 5.1.15 on 2026-06-21 18:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_volunteerapplication_cv_asset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('posted_by', models.ForeignKey(blank=True, db_column='posted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_role', models.ForeignKey(blank=True, db_column='target_role_id', help_text='Null = visible to all accepted volunteers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='volunteers.volunteerrole')),
            ],
            options={
                'db_table': 'volunteer_announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('due_label', models.CharField(blank=True, help_text='e.g. "Day 1, 08:00 AM"', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], db_index=True, default='pending', max_length=16)),
                ('application', models.ForeignKey(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='volunteers.volunteerapplication')),
                ('assigned_by', models.ForeignKey(blank=True, db_column='assigned_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('target_role', models.ForeignKey(blank=True, db_column='target_role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='volunteers.volunteerrole')),
            ],
            options={
                'db_table': 'volunteer_tasks',
                'ordering': ['status', 'created_at'],
            },
        ),
    ]
